# 00A — Check and repair corrected source-Zarr metadata

Run this **before retrying source loading in notebook 00**. Keep it beside your existing
`pilot_config.json`, `cosmx_rgb_pilot.py`, and the new `cosmx_zarr_schema_tools.py`.
Your edited config is read, not replaced.

The traceback fails before FOV layout or Cellpose. In SpatialData 0.7.2, container
format `0.1` uses legacy `multiscales` raster attributes, whereas container format
`0.2` uses `ome`. Those format numbers are **not** the installed package versions.

This notebook audits first. Applying a repair is explicit and only changes a verified
legacy root declaration and its consolidated metadata cache. Raster data, existing
image flips, label IDs, transcript coordinates, transformations, and AnnData contents
are not changed. Stop other writers to these source stores before applying it.

Sources: [reader, v0.7.2](https://raw.githubusercontent.com/scverse/spatialdata/v0.7.2/src/spatialdata/_io/io_zarr.py),
[metadata writer, v0.7.2](https://raw.githubusercontent.com/scverse/spatialdata/v0.7.2/src/spatialdata/_core/spatialdata.py).

In [1]:
from pathlib import Path
import sys
import importlib
import json
import pandas as pd

HERE = Path.cwd()  # Change only if the notebook is not in the bundle directory.
for filename in ("pilot_config.json", "cosmx_rgb_pilot.py", "cosmx_zarr_schema_tools.py"):
    if not (HERE / filename).is_file():
        raise FileNotFoundError(f"Set HERE to the bundle directory. Missing: {HERE / filename}")
if str(HERE) not in sys.path:
    sys.path.insert(0, str(HERE))
import cosmx_zarr_schema_tools as schema
importlib.reload(schema)
config = json.loads((HERE / "pilot_config.json").read_text())

ORIGINAL_ROOT = Path(
    "/stash/data/nonclin/TBIO-7804_CosMx6k-DS2025022748371-CRC/"
    "derived_files/batch_202506/zarr_files"
)
REFERENCE_FILES = {
    "B20317610105_colon": "B20317610105_colon_202508.zarr",
    "B20971880114_colon": "B20971880114_colon_202508.zarr",
}
SAMPLE_KEYS = list(config["samples"])
plans = {
    key: {
        "corrected": Path(config["samples"][key]["source_zarr"]),
        "reference": ORIGINAL_ROOT / REFERENCE_FILES[key],
    }
    for key in SAMPLE_KEYS
}
display(pd.DataFrame(plans).T)

,corrected,reference
B20317610105_colon,/host_root/nethome/reny28/Projects/CosMX_proje...,/stash/data/nonclin/TBIO-7804_CosMx6k-DS202502...
B20971880114_colon,/host_root/nethome/reny28/Projects/CosMX_proje...,/stash/data/nonclin/TBIO-7804_CosMx6k-DS202502...

## 1. Read-only audit

The audit reads actual on-disk metadata, ignoring the consolidated snapshot.
It checks all image/label elements, not only the first FOV.

Possible actions:
- `restore_legacy_container_0.1`: every raster is a supported legacy raster, but the root declares 0.2.
- `discard_stale_consolidated_cache`: the root is already correct; its cached metadata is outdated.
- `none`: no issue within this audit's scope.
- `stop_manual_review`: mixed formats, incomplete groups, missing/mismatched rasters, or another unsupported case.

A temporary `backup_*` group is reported, never automatically deleted. This audit checks
metadata and array descriptors, not every pixel/transcript payload chunk.

In [2]:
audits = {}
rows = []
for key, paths in plans.items():
    print("\nAUDIT:", key)
    info, raster_report = schema.audit_source_zarr(
        paths["corrected"], reference_path=paths["reference"]
    )
    audits[key] = (info, raster_report)
    rows.append({
        "sample": key,
        "root_version": info["root_container_version"],
        "rasters_expect": info["raster_expected_container"],
        "original_version": info["reference_version"],
        "zarr_on_disk": info["storage_zarr_format"],
        "images": info["n_images"],
        "labels": info["n_labels"],
        "stale_cache": info["consolidated_cache"]["stale"],
        "action": info["action"],
    })
    display(raster_report[["path", "family", "legacy_versions", "ome_version", "temporary_name", "error"]].head(8))
    if info["errors"]:
        print("REVIEW REQUIRED:\n" + "\n".join(info["errors"]))
        display(raster_report[raster_report["error"].notna() | raster_report["temporary_name"]])
    if info["consolidated_cache"]["stale"]:
        print("Stale-cache examples:", info["consolidated_cache"]["examples"])
audit_summary = pd.DataFrame(rows)
display(audit_summary)

AUDIT: B20317610105_colon

,path,family,legacy_versions,ome_version,temporary_name,error
0,images/100_image,legacy_multiscales,[0.4-dev-spatialdata],None,False,None
1,images/101_image,legacy_multiscales,[0.4-dev-spatialdata],None,False,None
2,images/102_image,legacy_multiscales,[0.4-dev-spatialdata],None,False,None
3,images/103_image,legacy_multiscales,[0.4-dev-spatialdata],None,False,None
4,images/104_image,legacy_multiscales,[0.4-dev-spatialdata],None,False,None
5,images/105_image,legacy_multiscales,[0.4-dev-spatialdata],None,False,None
6,images/106_image,legacy_multiscales,[0.4-dev-spatialdata],None,False,None
7,images/107_image,legacy_multiscales,[0.4-dev-spatialdata],None,False,None

Stale-cache examples: ['images/.zattrs (cache only)', 'images/.zgroup', 'images/100_image/.zgroup', 'images/100_image/0/.zattrs (cache only)', 'images/101_image/.zgroup', 'images/101_image/0/.zattrs (cache only)', 'images/102_image/.zgroup', 'images/102_image/0/.zattrs (cache only)', 'images/103_image/.zgroup', 'images/103_image/0/.zattrs (cache only)', 'images/104_image/.zgroup', 'images/104_image/0/.zattrs (cache only)', 'images/105_image/.zgroup', 'images/105_image/0/.zattrs (cache only)', 'images/106_image/.zgroup', 'images/106_image/0/.zattrs (cache only)', 'images/107_image/.zgroup', 'images/107_image/0/.zattrs (cache only)', 'images/108_image/.zgroup', 'images/108_image/0/.zattrs (cache only)']

AUDIT: B20971880114_colon

,path,family,legacy_versions,ome_version,temporary_name,error
0,images/100_image,legacy_multiscales,[0.4-dev-spatialdata],None,False,None
1,images/101_image,legacy_multiscales,[0.4-dev-spatialdata],None,False,None
2,images/102_image,legacy_multiscales,[0.4-dev-spatialdata],None,False,None
3,images/103_image,legacy_multiscales,[0.4-dev-spatialdata],None,False,None
4,images/104_image,legacy_multiscales,[0.4-dev-spatialdata],None,False,None
5,images/105_image,legacy_multiscales,[0.4-dev-spatialdata],None,False,None
6,images/106_image,legacy_multiscales,[0.4-dev-spatialdata],None,False,None
7,images/107_image,legacy_multiscales,[0.4-dev-spatialdata],None,False,None

Stale-cache examples: ['images/.zattrs (cache only)', 'images/.zgroup', 'images/100_image/.zgroup', 'images/100_image/0/.zattrs (cache only)', 'images/101_image/.zgroup', 'images/101_image/0/.zattrs (cache only)', 'images/102_image/.zgroup', 'images/102_image/0/.zattrs (cache only)', 'images/103_image/.zgroup', 'images/103_image/0/.zattrs (cache only)', 'images/104_image/.zgroup', 'images/104_image/0/.zattrs (cache only)', 'images/105_image/.zgroup', 'images/105_image/0/.zattrs (cache only)', 'images/106_image/.zgroup', 'images/106_image/0/.zattrs (cache only)', 'images/107_image/.zgroup', 'images/107_image/0/.zattrs (cache only)', 'images/108_image/.zgroup', 'images/108_image/0/.zattrs (cache only)']

,sample,root_version,rasters_expect,original_version,zarr_on_disk,images,labels,stale_cache,action
0,B20317610105_colon,0.2,0.1,0.1,2,200,200,True,restore_legacy_container_0.1
1,B20971880114_colon,0.2,0.1,0.1,2,200,200,True,restore_legacy_container_0.1

## 2. Explicit, one-time repair

First run with `APPLY_REPAIR=False`. After reviewing the audit and stopping other source-store
writers, set it to `True` and rerun this cell.

The helper verifies the corrected rasters against the originals, backs up the exact root
metadata/cache files in an external sibling directory, preserves all unrelated attributes,
and changes only the necessary root version field. It invalidates `.zmetadata` so a stale
snapshot cannot override the fix. No image/label arrays, table contents or transforms are rewritten.
Re-running after successful repair is a no-op. A mixed or partial store is refused.

In [3]:
APPLY_REPAIR = False  # Set True only after inspecting the previous cell.
repair_results = {}
for key, paths in plans.items():
    print("\nREPAIR PLAN:", key)
    repair_results[key] = schema.repair_source_zarr_metadata(
        paths["corrected"],
        reference_path=paths["reference"],
        apply=APPLY_REPAIR,
    )
display(pd.DataFrame([
    {"sample": key, "status": result["status"], "changed": result["changed"],
     "backup_path": result["backup_path"]}
    for key, result in repair_results.items()
]))

REPAIR PLAN: B20317610105_colon
[schema] B20317610105_colon_202508.zarr: declared=0.2, rasters expect=0.1, action=restore_legacy_container_0.1
[dry run] No source files changed. Set apply=True after reviewing the audit.

REPAIR PLAN: B20971880114_colon
[schema] B20971880114_colon_202508.zarr: declared=0.2, rasters expect=0.1, action=restore_legacy_container_0.1
[dry run] No source files changed. Set apply=True after reviewing the audit.

               sample   status  changed backup_path
0  B20317610105_colon  dry_run    False        None
1  B20971880114_colon  dry_run    False        None

In [4]:
# now replicated and change to True for actual repair
APPLY_REPAIR = True  # Set True only after inspecting the previous cell.
repair_results = {}
for key, paths in plans.items():
    print("\nREPAIR PLAN:", key)
    repair_results[key] = schema.repair_source_zarr_metadata(
        paths["corrected"],
        reference_path=paths["reference"],
        apply=APPLY_REPAIR,
    )
display(pd.DataFrame([
    {"sample": key, "status": result["status"], "changed": result["changed"],
     "backup_path": result["backup_path"]}
    for key, result in repair_results.items()
]))

REPAIR PLAN: B20317610105_colon
[schema] B20317610105_colon_202508.zarr: declared=0.2, rasters expect=0.1, action=restore_legacy_container_0.1
[backup] /host_root/nethome/reny28/Projects/CosMX_projects/P06364_CRC_DS20250227_48371/tmp/DS-20250227-48371/B20317610105_colon_202508.zarr.schema_backup_20260916T203924Z_b76e5387
[done] Root declaration/cache repaired. Rasters, points, tables and transforms untouched.
[next] Strict-load with pilot.load_source(...). Re-consolidation is optional after validation.

REPAIR PLAN: B20971880114_colon
[schema] B20971880114_colon_202508.zarr: declared=0.2, rasters expect=0.1, action=restore_legacy_container_0.1
[backup] /host_root/nethome/reny28/Projects/CosMX_projects/P06364_CRC_DS20250227_48371/tmp/DS-20250227-48371/B20971880114_colon_202508.zarr.schema_backup_20260916T203950Z_6585f637
[done] Root declaration/cache repaired. Rasters, points, tables and transforms untouched.
[next] Strict-load with pilot.load_source(...). Re-consolidation is optional after validation.

,sample,status,changed,backup_path
0,B20317610105_colon,metadata_repaired,True,/host_root/nethome/reny28/Projects/CosMX_proje...
1,B20971880114_colon,metadata_repaired,True,/host_root/nethome/reny28/Projects/CosMX_proje...

## 3. Verify with the original strict pilot loader

This uses the same `pilot.load_source()` that failed in notebook 00. It does not use
`on_bad_files="warn"` or omit labels. The per-FOV pairing check verifies that each image has
its corresponding labels and points and that full-resolution image/label dimensions agree.
The table is loaded normally; this is not a complete pixel/chunk integrity test.

In [5]:
import cosmx_rgb_pilot as pilot
importlib.reload(pilot)
verification_rows = []
for key, paths in plans.items():
    info, _ = schema.audit_source_zarr(paths["corrected"], reference_path=paths["reference"])
    if info["action"] != "none":
        raise RuntimeError(f"{key}: finish the audit/repair first; pending action={info['action']}")
    source = pilot.load_source(paths["corrected"])
    pairs = pilot.discover_fovs(source, config["samples"][key])
    verification_rows.append({
        "sample": key,
        "images": len(source.images),
        "labels": len(source.labels),
        "points": len(source.points),
        "tables": len(source.tables),
        "complete_fov_pairs": len(pairs),
        "status": "strict_load_ok",
    })
    del source
verification = pd.DataFrame(verification_rows)
display(verification)

/home/domino/reny28/Projects/CosMX_projects/P06364_CRC_DS20250227_48371/env/gpu_env/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/home/domino/reny28/Projects/CosMX_projects/P06364_CRC_DS20250227_48371/env/gpu_env/.venv/lib/python3.13/site-packages/spatialdata/_core/query/relational_query.py:531: FutureWarning: functools.partial will be a method descriptor in future Python versions; wrap it in enum.member() if you want to preserve the old behavior
  left = partial(_left_join_spatialelement_table)
/home/domino/reny28/Projects/CosMX_projects/P06364_CRC_DS20250227_48371/env/gpu_env/.venv/lib/python3.13/site-packages/spatialdata/_core/query/relational_query.py:532: FutureWarning: functools.partial will be a method descriptor in future Python versions; wrap it in enum.member() if you want to preserve the old behavior
  left_exclusive = partial(_left_exclusive_join_spatialelement_table)
/home/domino/reny28/Projects/CosMX_projects/P06364_CRC_DS20250227_48371/env/gpu_env/.venv/lib/python3.13/site-packages/spatialdata/_core/query/relational_query.py:533: FutureWarning: functools.partial will be a method descriptor in future Python versions; wrap it in enum.member() if you want to preserve the old behavior
  inner = partial(_inner_join_spatialelement_table)
/home/domino/reny28/Projects/CosMX_projects/P06364_CRC_DS20250227_48371/env/gpu_env/.venv/lib/python3.13/site-packages/spatialdata/_core/query/relational_query.py:534: FutureWarning: functools.partial will be a method descriptor in future Python versions; wrap it in enum.member() if you want to preserve the old behavior
  right = partial(_right_join_spatialelement_table)
/home/domino/reny28/Projects/CosMX_projects/P06364_CRC_DS20250227_48371/env/gpu_env/.venv/lib/python3.13/site-packages/spatialdata/_core/query/relational_query.py:535: FutureWarning: functools.partial will be a method descriptor in future Python versions; wrap it in enum.member() if you want to preserve the old behavior
  right_exclusive = partial(_right_exclusive_join_spatialelement_table)
/home/domino/reny28/Projects/CosMX_projects/P06364_CRC_DS20250227_48371/code/Python/cosmx_cpsamv2_softstitch_pilot/cosmx_rgb_pilot.py:88: UserWarning: SpatialData is not stored in the most current format. If you want to use Zarr v3, please write the store to a new location using `sdata.write()`.
  return sd.read_zarr(str(path))
no parent found for <ome_zarr.reader.Label object at 0x7fc785fd2a50>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc785fce0d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc785fcda90>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc7742c3a80>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc7742c3490>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc803983650>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc7743f68b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc7743f7240>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc774202550>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc774202a50>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc785f56b70>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc785f568a0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c290ad0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c23cad0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c2181f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c2ce8d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c2ce510>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c130260>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc7742917b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c3620d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c360ff0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc7741a7140>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c1fe1d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c110e50>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c1759b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c175be0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c12a690>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c17aa50>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c17b830>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c17b710>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c17b230>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c17a390>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c12ad50>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c171d30>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c172b10>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c1738f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c1733b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c1714f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c17a6f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c184f50>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c185d30>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c186b10>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c1720f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c171550>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c14a270>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c14a8d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c1849b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c184b90>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c1849b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c14a5d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c14a8d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c135790>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c136570>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c137350>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c178ef0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c14aa50>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c134c50>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c135790>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c1d9790>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c1da570>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c134c50>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c185850>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c1d8950>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c1d8290>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c1d8230>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c19d2b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c1db410>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c1d92b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c1d8fb0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c19cb30>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c19f1d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c19f0b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c1b0dd0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c19f7d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c19e090>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c19c470>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c1b21b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c1b3050>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c1b2ff0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c1b3710>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c1b0b30>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c1b2b10>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c19db50>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c1d1d90>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c1d2b70>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c19eb70>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c1b2630>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c1b2990>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c1d1670>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c154ad0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c1558b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c1d3170>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c185850>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c1b38f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c156ed0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c157b90>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc7403ccad0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc7403cd8b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c155f70>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c1566f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c1561b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc7403cec90>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc7403cf770>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc7403009b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc7403cf710>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc7403ce390>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c1563f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc740300290>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc740302870>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc740303650>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc740303e30>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc740303c50>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c154b90>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc7403cecf0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc7403415b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc740342390>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc740343170>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc740343ef0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc740341c70>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc740341c10>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc7403ce030>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c1b1550>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c1373b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c137ad0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc7403ce030>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc7403cd430>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc740341c10>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc740369a30>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc74036a810>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc740341c10>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c1dbe90>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c1dbcb0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc7403694f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc740369550>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc74031d550>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc74031e330>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc74036b9b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc74036a090>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc74031c7d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc74031f710>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc74031f590>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc7403b93d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc74031ffb0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc74031dcd0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc74031f2f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc7403b8050>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc7403bb2f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc7403bb1d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc7403e0ef0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc7403bb950>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc7403b9d30>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc7403b85f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc7403e1850>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc7403e2c90>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc7403e3ad0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc7403e2c30>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc7403e34d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc7403e2c90>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc7403b85f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc7402019d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc7402027b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc740203590>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc7402030b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc740202090>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc7403e0c50>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc7403e2090>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc74021d850>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc74021e630>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc7403e01d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc740202f30>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc740200f50>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc74021c110>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc74021d190>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc740235370>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc740236150>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc74021c050>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc740200f50>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc7402350d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc740237530>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc7402373b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc7402491f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc7402373b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc740237d70>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc740236ab0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc740248cb0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc74024b110>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc74024b0b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc740268d10>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc740248d10>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc740249af0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc740249a90>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc74026a0f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc74026af90>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc74026af30>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc740249fd0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc74026b050>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc740269cd0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc740269a90>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc7402035f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc74031e3f0>: None
/home/domino/reny28/Projects/CosMX_projects/P06364_CRC_DS20250227_48371/code/Python/cosmx_cpsamv2_softstitch_pilot/cosmx_rgb_pilot.py:88: UserWarning: SpatialData is not stored in the most current format. If you want to use Zarr v3, please write the store to a new location using `sdata.write()`.
  return sd.read_zarr(str(path))
no parent found for <ome_zarr.reader.Label object at 0x7fc839a438f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c284f50>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc7403cf350>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc7402c2ed0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc7402c2390>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc740271a30>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c241d30>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc7402719d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc740302b70>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c2e7170>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c242330>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c243470>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c2430b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c2a0ef0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c243b30>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c240bf0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c2874d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c2a1850>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c2a2c90>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c2a3ad0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c2a39b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c2a3530>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c2a0950>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c242c30>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c2211f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c222630>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c223410>: None
no parent found for <ome_zarr.reader.Label object at 0x7fc75c2232f0>: None

,sample,images,labels,points,tables,complete_fov_pairs,status
0,B20317610105_colon,200,200,200,1,200,strict_load_ok
1,B20971880114_colon,200,200,200,1,200,strict_load_ok

## 4. Optional: rebuild the consolidated metadata cache after successful loading

This improves later metadata access; it is not required for correctness. It does **not**
call `sdata.write_metadata()` or change the root format declaration. Leave disabled for the
first successful pass. Do not run concurrent source-store writes during consolidation.

In [6]:
RECONSOLIDATE_AFTER_SUCCESS = False
if RECONSOLIDATE_AFTER_SUCCESS:
    import zarr
    if len(verification_rows) != len(plans):
        raise RuntimeError("Finish strict-load verification for every source first.")
    for key, paths in plans.items():
        zarr.consolidate_metadata(str(paths["corrected"]))
        info, _ = schema.audit_source_zarr(paths["corrected"], reference_path=paths["reference"])
        if info["action"] != "none":
            raise RuntimeError(f"Consolidation did not pass audit for {key}: {info}")
        check = pilot.load_source(paths["corrected"])
        print(key, "reconsolidated and strict-loaded:", len(check.images), len(check.labels))
        del check
else:
    print("Optional cache rebuild not requested.")

Optional cache rebuild not requested.

In [7]:
# rerun to actually rebuild dataset so that we don't run into this again...
RECONSOLIDATE_AFTER_SUCCESS = True
if RECONSOLIDATE_AFTER_SUCCESS:
    import zarr
    if len(verification_rows) != len(plans):
        raise RuntimeError("Finish strict-load verification for every source first.")
    for key, paths in plans.items():
        zarr.consolidate_metadata(str(paths["corrected"]))
        info, _ = schema.audit_source_zarr(paths["corrected"], reference_path=paths["reference"])
        if info["action"] != "none":
            raise RuntimeError(f"Consolidation did not pass audit for {key}: {info}")
        check = pilot.load_source(paths["corrected"])
        print(key, "reconsolidated and strict-loaded:", len(check.images), len(check.labels))
        del check
else:
    print("Optional cache rebuild not requested.")

/home/domino/reny28/Projects/CosMX_projects/P06364_CRC_DS20250227_48371/env/gpu_env/.venv/lib/python3.13/site-packages/zarr/core/group.py:3559: ZarrUserWarning: Object at zmetadata is not recognized as a component of a Zarr hierarchy.
  warnings.warn(
/home/domino/reny28/Projects/CosMX_projects/P06364_CRC_DS20250227_48371/env/gpu_env/.venv/lib/python3.13/site-packages/zarr/core/group.py:3559: ZarrUserWarning: Object at points.parquet is not recognized as a component of a Zarr hierarchy.
  warnings.warn(

RuntimeError: Consolidation did not pass audit for B20317610105_colon: {'path': '/host_root/nethome/reny28/Projects/CosMX_projects/P06364_CRC_DS20250227_48371/tmp/DS-20250227-48371/B20317610105_colon_202508.zarr', 'root_container_version': '0.1', 'raster_expected_container': '0.1', 'storage_zarr_format': 2, 'n_images': 200, 'n_labels': 200, 'raster_families': {'legacy_multiscales': 400}, 'consolidated_cache': {'present': True, 'stale': True, 'examples': ['images/.zattrs (cache only)', 'images/.zgroup', 'images/100_image/.zgroup', 'images/100_image/0/.zattrs (cache only)', 'images/101_image/.zgroup', 'images/101_image/0/.zattrs (cache only)', 'images/102_image/.zgroup', 'images/102_image/0/.zattrs (cache only)', 'images/103_image/.zgroup', 'images/103_image/0/.zattrs (cache only)', 'images/104_image/.zgroup', 'images/104_image/0/.zattrs (cache only)', 'images/105_image/.zgroup', 'images/105_image/0/.zattrs (cache only)', 'images/106_image/.zgroup', 'images/106_image/0/.zattrs (cache only)', 'images/107_image/.zgroup', 'images/107_image/0/.zattrs (cache only)', 'images/108_image/.zgroup', 'images/108_image/0/.zattrs (cache only)']}, 'reference_version': '0.1', 'reference_checked': True, 'action': 'discard_stale_consolidated_cache', 'errors': []}

## Return to notebook 00

Rerun notebook 00's source-loading block. Keep the corrected paths in your existing config.
Do not run image-flip or point-repair functions again for this metadata problem.

In the **orientation-decision** cell, use `image_flip_y=False` when inspection confirms the
saved image already agrees with transcript coordinates. Determine `label_flip_y` separately;
do not assume labels and images were corrected identically. Keep approval false until reviewed.

When changing from raw sources to physically corrected sources, distinguish their revisions
(e.g. `source_revision="image_corrected_202508_v1"`). If a previous successful run cached a
layout for the raw sources, use a new pilot output root rather than bypassing its cache checks.
The root metadata repair itself does not change pixels or coordinates.

### Prevent recurrence
A broad `sdata.write_metadata()` call in SpatialData 0.7.2 defaults to writing root attributes
using the current container format. For table/transform-only changes, use the corresponding
scoped persistence operations and keep root-format rewriting explicit. The previous
`persist_changes` version must actually omit its unconditional `sdata.write_metadata()` call;
merely changing the loading code will not prevent a later persistence call from reintroducing it.

### Validation of this supplement
The helper passed 19 synthetic JSON/directory-fixture tests; this notebook is syntax-checked
and nbformat-validated. Your actual source stores and exact SpatialData/Zarr runtime were not
available here. The strict-load cell is the instance-side verification.