# 06 • Register overlapping acquisitions and audit transcript duplication

**New upstream pilot stage: do not run segmentation until registration has been reviewed.**

This notebook reads the exact selected windows from notebook 00 and expands to nearby source
FOVs for registration context. It keeps your reviewed image/label flips and does not edit any
source Zarr. `rgb_v2_legacy_thresholds` is frozen for the later before/after experiment.

The first implementation uses the installed SciPy/scikit-image stack: normalized template
correlation on multiple independent border strips, followed by a translation-graph solve.
It does not require HALO or a package upgrade. `multiview-stitcher` remains a good candidate
for scaling the registration backend after this selected-field test.

**Not a whole-sample stitch:** disjoint selected neighborhoods are anchored independently to
one original FOV. Do not concatenate their cell outputs into a single biological sample yet.

References: [scikit-image template correlation](https://scikit-image.org/docs/0.26.x/api/skimage.feature.html#skimage.feature.match_template),
[SciPy inverse image resampling](https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.affine_transform.html),
[multiview-stitcher registration design](https://multiview-stitcher.github.io/multiview-stitcher/main/registration_overview/).

In [1]:
from pathlib import Path
import sys, importlib, json
import numpy as np
import pandas as pd

HERE = Path.cwd()  # Set to the existing pilot directory if necessary.
for name in ('cosmx_rgb_pilot.py', 'cosmx_pilot_review.py', 'cosmx_overlap_stitch.py', 'pilot_config.json'):
    if not (HERE / name).is_file():
        raise FileNotFoundError(f"Keep the add-on beside the existing pilot bundle. Missing {HERE / name}")
if str(HERE) not in sys.path:
    sys.path.insert(0, str(HERE))
import cosmx_rgb_pilot as pilot
import cosmx_pilot_review as review
import cosmx_overlap_stitch as stitch
importlib.reload(pilot)
importlib.reload(review)
importlib.reload(stitch)

# Your edited baseline configuration is read, never overwritten.
config = pilot.read_json(HERE / 'pilot_config.json')
BASELINE_ROOT = Path(config['output_root'])
WORKSPACE = BASELINE_ROOT.with_name(BASELINE_ROOT.name + '_registered_owner_v1')
SAMPLE_KEYS = list(config['samples'])  # Both colon samples by default.
print('Baseline:', BASELINE_ROOT)
print('New registered workspace:', WORKSPACE)
print('Add-on version:', stitch.VERSION)
print('Samples:', SAMPLE_KEYS)

Baseline: /host_root/nethome/reny28/Projects/CosMX_projects/P06364_CRC_DS20250227_48371/tmp/DS-20250227-48371/cpsam_v2_rgb_softstitch_pilot_v1
New registered workspace: /host_root/nethome/reny28/Projects/CosMX_projects/P06364_CRC_DS20250227_48371/tmp/DS-20250227-48371/cpsam_v2_rgb_softstitch_pilot_v1_registered_owner_v1
Add-on version: 1.0.0
Samples: ['B20317610105_colon', 'B20971880114_colon']

## 1. Inventory the selected fields and freeze a registration recipe

Only source FOVs around these windows are used. The routine tests image content; it does not
assume that metadata saying “abut” means there is no physical overlap. Default search parameters
cover roughly **28–280 px of normal overlap** and **±64 px tangential displacement**. They are
search bounds, not assertions that every seam has 50 or 100 px overlap.

The blue composite channel is used for registration; final segmentation still uses all RGB
channels. `green`, `red`, and `rgb_mean` can be tested in a **new workspace revision** when the
blue channel has insufficient structure. Do not lower quality gates merely to force acceptance.

In [2]:
REGISTRATION_OPTIONS = dict(stitch.DEFAULT_REGISTRATION)
# Examples of a deliberate new experiment:
# REGISTRATION_OPTIONS['channel'] = 'rgb_mean'
# WORKSPACE = BASELINE_ROOT.with_name(BASELINE_ROOT.name + '_registered_owner_rgbmean_v2')

scope_rows = []
for sample in SAMPLE_KEYS:
    layout, selected_tiles, input_hashes = stitch.selected_plan(config, sample)
    scope = stitch.registration_scope(layout, selected_tiles, REGISTRATION_OPTIONS)
    pairs = stitch.candidate_pairs(scope,
        tolerance_px=REGISTRATION_OPTIONS['candidate_edge_tolerance_px'],
        min_shared_px=REGISTRATION_OPTIONS['min_shared_edge_px'])
    for tile in selected_tiles:
        scope_rows.append({'sample': sample, 'tile': tile['tile_id'],
                           'reason': tile.get('reason', ''),
                           'original_FOVs_in_context': len(scope),
                           'candidate_edges_in_context': len(pairs)})
display(pd.DataFrame(scope_rows))
display(pd.Series(REGISTRATION_OPTIONS, name='registration_recipe'))

,sample,tile,reason,original_FOVs_in_context,candidate_edges_in_context
0,B20317610105_colon,pilot_00_vertical_seam,vertical_seam,18,23
1,B20317610105_colon,pilot_01_horizontal_seam,horizontal_seam,18,23
2,B20317610105_colon,pilot_02_four_fov_junction,four_fov_junction,18,23
3,B20317610105_colon,pilot_03_dense_interior,dense_interior,18,23
4,B20971880114_colon,pilot_00_vertical_seam,vertical_seam,25,30
5,B20971880114_colon,pilot_01_horizontal_seam,horizontal_seam,25,30
6,B20971880114_colon,pilot_02_four_fov_junction,four_fov_junction,25,30
7,B20971880114_colon,pilot_03_dense_interior,dense_interior,25,30

channel                        blue
search_depth_px                 256
template_width_px                24
edge_inset_px                     4
tangent_length_px               384
tangent_search_px                64
n_strips                          5
candidate_edge_tolerance_px     320
min_shared_edge_px              512
highpass_sigma_px               8.0
min_ncc                        0.45
min_peak_margin                0.03
peak_exclusion_px                 6
max_strip_deviation_px          3.0
max_holdout_error_px            3.0
max_graph_residual_px           3.0
context_margin_px               512
max_component_shift_px         1536
Name: registration_recipe, dtype: object

## 2. Fit image-based translations; save strip and graph diagnostics

Five nonoverlapping strips are sampled along each source edge. Alternating strips estimate the
translation; the other strips validate it. Low-texture, ambiguous, search-boundary, or inconsistent
matches are rejected. A graph solve checks consistency where loops exist. A tree has no loop
constraint, so visual inspection remains necessary.

`candidate_pass` is **not approval**. Templates with repeated crypt/cell patterns can create false
matches even with high correlation. Inspect the registered source-A/source-B landmarks below.

Runs resume by request hash. A changed source, selected tile, orientation, recipe, or manual
correction requires a new workspace; no stale result is silently reused.

In [3]:
RUN_REGISTRATION = True
MANUAL_EDGE_CORRECTIONS = {}  # Optional, sample -> pair_id -> explicitly reviewed dx/dy/reason.
# Example format only; never insert an unverified shift:
# {'B20317610105_colon': {'12__13__vertical':
#     {'dx_px': -50.0, 'dy_px': 0.0, 'reviewed': True, 'reason': 'Landmarks manually verified'}}}

candidates = {}
for sample in SAMPLE_KEYS:
    if RUN_REGISTRATION:
        candidate, pair_qc, strip_qc = stitch.register_selected_sample(
            config, sample, WORKSPACE, options=REGISTRATION_OPTIONS,
            manual=MANUAL_EDGE_CORRECTIONS.get(sample))
    else:
        folder = WORKSPACE / sample / 'registration'
        candidate = pilot.read_json(folder / 'candidate.json')
        pair_qc = pd.read_csv(folder / 'pair_summary.csv')
    candidates[sample] = candidate
    print(sample, candidate['registration_status'])
    if candidate.get('blocking_error'):
        print(candidate['blocking_error'])
    display(pair_qc)
    if candidate['registration_status'] == 'candidate_ready':
        display(pd.read_csv(WORKSPACE / sample / 'registration' / 'graph_residuals.csv'))
        print('Solution hash:', candidate['solution_hash'])

[registration 1/23] B20317610105_colon 87__88__vertical

/home/domino/reny28/Projects/CosMX_projects/P06364_CRC_DS20250227_48371/env/gpu_env/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/home/domino/reny28/Projects/CosMX_projects/P06364_CRC_DS20250227_48371/env/gpu_env/.venv/lib/python3.13/site-packages/spatialdata/_core/query/relational_query.py:531: FutureWarning: functools.partial will be a method descriptor in future Python versions; wrap it in enum.member() if you want to preserve the old behavior
  left = partial(_left_join_spatialelement_table)
/home/domino/reny28/Projects/CosMX_projects/P06364_CRC_DS20250227_48371/env/gpu_env/.venv/lib/python3.13/site-packages/spatialdata/_core/query/relational_query.py:532: FutureWarning: functools.partial will be a method descriptor in future Python versions; wrap it in enum.member() if you want to preserve the old behavior
  left_exclusive = partial(_left_exclusive_join_spatialelement_table)
/home/domino/reny28/Projects/CosMX_projects/P06364_CRC_DS20250227_48371/env/gpu_env/.venv/lib/python3.13/site-packages/spatialdata/_core/query/relational_query.py:533: FutureWarning: functools.partial will be a method descriptor in future Python versions; wrap it in enum.member() if you want to preserve the old behavior
  inner = partial(_inner_join_spatialelement_table)
/home/domino/reny28/Projects/CosMX_projects/P06364_CRC_DS20250227_48371/env/gpu_env/.venv/lib/python3.13/site-packages/spatialdata/_core/query/relational_query.py:534: FutureWarning: functools.partial will be a method descriptor in future Python versions; wrap it in enum.member() if you want to preserve the old behavior
  right = partial(_right_join_spatialelement_table)
/home/domino/reny28/Projects/CosMX_projects/P06364_CRC_DS20250227_48371/env/gpu_env/.venv/lib/python3.13/site-packages/spatialdata/_core/query/relational_query.py:535: FutureWarning: functools.partial will be a method descriptor in future Python versions; wrap it in enum.member() if you want to preserve the old behavior
  right_exclusive = partial(_right_exclusive_join_spatialelement_table)
/home/domino/reny28/Projects/CosMX_projects/P06364_CRC_DS20250227_48371/code/Python/cosmx_cpsamv2_softstitch_pilot/cosmx_rgb_pilot.py:88: UserWarning: SpatialData is not stored in the most current format. If you want to use Zarr v3, please write the store to a new location using `sdata.write()`.
  return sd.read_zarr(str(path))
no parent found for <ome_zarr.reader.Label object at 0x7f41fc46b620>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41ffee9950>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41ffee9d10>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fc303ce0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fc303360>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7f05fd0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fff15ae0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fff159d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fc36d650>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41ffe25650>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fc48eb70>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fc48ed50>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7fadfd0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7e10910>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7f66410>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7e08c50>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7e090d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7f42990>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7f40260>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7f1d450>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7f1e530>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fc4f3d10>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fc23c0d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7f46ed0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7e21470>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7e22270>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7e38b90>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7e28230>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7e28ad0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7e38a10>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7e389b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7e3b110>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7e54290>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7e54d10>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7e3b2f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7e389b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7e56150>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7e55bb0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7e56f90>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7e6c110>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7e57350>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7e56690>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7e3b2f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7e6ca10>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7e6dcd0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7e6eab0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7e6eff0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7e6eab0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7e6c2f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7e56150>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7ea0fb0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7ea1b50>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7ea2930>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7ea3830>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7ea2d50>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7ea1eb0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7e6ec90>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7ebc890>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7ebd670>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7ebe450>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7ea0050>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7ebde50>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7ebcc50>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7ebcd10>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7eac710>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7ead4f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7ebff50>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7ebc530>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7eae630>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7eacb30>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7eaf410>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7ef0590>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7ef1010>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7eaf2f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7ebe0f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7ea1130>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7e55910>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7e57cb0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7ff3d10>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fc34dcd0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7ea2e70>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7eaf5f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fc6b4290>: None
no parent found for <ome_zarr.reader.Label object at 0x7f4272bfd7f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f422fb21fd0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7ebd850>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7ef1370>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7ef2f90>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d0c110>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d0cb90>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7ef3350>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7ea1970>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d0ca70>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d0c230>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d0ef90>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d188f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d0f350>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d0eed0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7ea1970>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d18230>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d1a1b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d1af90>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d1bad0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d1a5d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d18410>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d1c890>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d1d3d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d1e1b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d0e6f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d1f770>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d1e5d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d1e030>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7f8c950>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7f8d3d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d1fb30>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d0d0d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7f8d7f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7f8c530>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7f8ef30>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d35130>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7f8fa70>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7f8c4d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d353d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d34530>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d369f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d36f30>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d37bf0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d35f10>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7f8c470>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d4d970>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d4dc10>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d4e9f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d4fa70>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d4f050>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d4e930>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d642f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d64e30>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d65c10>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d347d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d4c290>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d64b90>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d644d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d843b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d84e30>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d85c10>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d667b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d84e30>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d84d10>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d87230>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7da03b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7da0e30>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d675f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d84cb0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d4f7d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d37a70>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d1bd10>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d1b2f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7e28230>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d1ff50>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d86750>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7da1010>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7da1eb0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7da3110>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7db0290>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7da2e70>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7da0590>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d1d190>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7db0dd0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7db21b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7db2f90>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7db3b90>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7db2ed0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d871d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7db8410>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7db8ef0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7db9cd0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7dbaab0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7db20f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7dbb830>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7db9310>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7dd8ad0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7dd8d70>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7dd9b50>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7db8dd0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7db1e50>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7dd9eb0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7dd9850>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7ddbe30>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7df8890>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7df9670>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7dd82f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7db1e50>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7dfab10>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7dfa510>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7dfb050>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7c10710>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7dfbf50>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7dfa5d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7dd9fd0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7c11250>: None

[registration 2/23] B20317610105_colon 99__87__horizontal
[registration 3/23] B20317610105_colon 88__89__vertical
[registration 4/23] B20317610105_colon 100__88__horizontal
[registration 5/23] B20317610105_colon 101__89__horizontal
[registration 6/23] B20317610105_colon 94__95__vertical
[registration 7/23] B20317610105_colon 106__94__horizontal
[registration 8/23] B20317610105_colon 95__96__vertical
[registration 9/23] B20317610105_colon 107__95__horizontal
[registration 10/23] B20317610105_colon 108__96__horizontal
[registration 11/23] B20317610105_colon 99__100__vertical
[registration 12/23] B20317610105_colon 111__99__horizontal
[registration 13/23] B20317610105_colon 100__101__vertical
[registration 14/23] B20317610105_colon 112__100__horizontal
[registration 15/23] B20317610105_colon 113__101__horizontal
[registration 16/23] B20317610105_colon 106__107__vertical
[registration 17/23] B20317610105_colon 107__108__vertical
[registration 18/23] B20317610105_colon 110__111__vertical
[registration 19/23] B20317610105_colon 122__110__horizontal
[registration 20/23] B20317610105_colon 111__112__vertical
[registration 21/23] B20317610105_colon 123__111__horizontal
[registration 22/23] B20317610105_colon 112__113__vertical
[registration 23/23] B20317610105_colon 122__123__vertical
[review required] Unresolved pair(s) disconnect the registration context. Review diagnostics, channel or manual corrections: ['99__87__horizontal', '100__88__horizontal', '101__89__horizontal', '94__95__vertical', '106__94__horizontal', '95__96__vertical', '107__95__horizontal', '108__96__horizontal', '99__100__vertical', '100__101__vertical', '112__100__horizontal', '113__101__horizontal', '106__107__vertical', '107__108__vertical', '110__111__vertical', '122__110__horizontal', '111__112__vertical', '123__111__horizontal', '112__113__vertical', '122__123__vertical']
B20317610105_colon needs_review
Unresolved pair(s) disconnect the registration context. Review diagnostics, channel or manual corrections: ['99__87__horizontal', '100__88__horizontal', '101__89__horizontal', '94__95__vertical', '106__94__horizontal', '95__96__vertical', '107__95__horizontal', '108__96__horizontal', '99__100__vertical', '100__101__vertical', '112__100__horizontal', '113__101__horizontal', '106__107__vertical', '107__108__vertical', '110__111__vertical', '122__110__horizontal', '111__112__vertical', '123__111__horizontal', '112__113__vertical', '122__123__vertical']

,pair_id,a,b,axis,nominal_gap_px,tangent0,tangent1,status,dx_px,dy_px,n_fit_good,n_holdout_good,fit_max_deviation_px,holdout_max_error_px,median_ncc,reason
0,87__88__vertical,87,88,vertical,0.0,59584.0,63840.0,candidate_pass,-50.167662,-8.967595,2,2,1.754043,1.656173,0.841386,fit and held-out strips agree
1,99__87__horizontal,99,87,horizontal,0.0,68096.0,72352.0,needs_review,9.272639,-48.811347,3,2,4.603935,4.692982,0.833332,strip shifts disagree
2,88__89__vertical,88,89,vertical,0.0,59584.0,63840.0,candidate_pass,-52.300299,-8.069557,2,1,1.991200,1.711192,0.838733,fit and held-out strips agree
3,100__88__horizontal,100,88,horizontal,0.0,72352.0,76608.0,needs_review,9.394796,-49.487675,3,2,4.311070,3.710744,0.915060,strip shifts disagree
4,101__89__horizontal,101,89,horizontal,0.0,76608.0,80864.0,needs_review,9.245901,-50.013414,3,2,4.363698,2.913475,0.859221,strip shifts disagree
5,94__95__vertical,94,95,vertical,0.0,55328.0,59584.0,needs_review,-44.674225,-9.307142,3,2,3.714558,3.461256,0.884100,strip shifts disagree
6,106__94__horizontal,106,94,horizontal,0.0,46816.0,51072.0,needs_review,9.053467,-49.465648,3,2,4.574442,3.944611,0.902285,strip shifts disagree
7,95__96__vertical,95,96,vertical,0.0,55328.0,59584.0,needs_review,-49.052841,-9.828856,3,2,3.525360,2.297000,0.897374,strip shifts disagree
8,107__95__horizontal,107,95,horizontal,0.0,51072.0,55328.0,needs_review,8.917737,-49.092932,3,2,4.441138,4.046201,0.899424,strip shifts disagree
9,108__96__horizontal,108,96,horizontal,0.0,55328.0,59584.0,needs_review,8.984808,-49.659706,3,2,3.948410,3.488802,0.829890,strip shifts disagree
10,99__100__vertical,99,100,vertical,0.0,55328.0,59584.0,needs_review,-49.555857,-9.381977,3,2,4.470717,2.263986,0.856638,strip shifts disagree
11,111__99__horizontal,111,99,horizontal,0.0,68096.0,72352.0,candidate_pass,9.796866,-51.729644,2,2,2.165858,2.074321,0.883154,fit and held-out strips agree
12,100__101__vertical,100,101,vertical,0.0,55328.0,59584.0,needs_review,-50.944043,-8.546750,2,2,3.255840,3.216178,0.914848,strip shifts disagree
13,112__100__horizontal,112,100,horizontal,0.0,72352.0,76608.0,needs_review,9.117587,-49.531341,3,2,4.289107,3.654677,0.834804,strip shifts disagree
14,113__101__horizontal,113,101,horizontal,0.0,76608.0,80864.0,needs_review,8.976331,-48.379523,3,2,5.238347,5.118782,0.872789,strip shifts disagree
15,106__107__vertical,106,107,vertical,0.0,51072.0,55328.0,needs_review,-43.635536,-9.466047,3,2,4.062945,4.063982,0.823545,strip shifts disagree
16,107__108__vertical,107,108,vertical,0.0,51072.0,55328.0,needs_review,-47.852576,-9.763804,3,2,3.845889,4.151177,0.935165,strip shifts disagree
17,110__111__vertical,110,111,vertical,0.0,51072.0,55328.0,needs_review,-49.790787,-9.697590,3,2,5.203516,4.030593,0.912300,strip shifts disagree
18,122__110__horizontal,122,110,horizontal,0.0,63840.0,68096.0,needs_review,8.899465,-48.807851,3,2,4.844066,3.889620,0.897316,strip shifts disagree
19,111__112__vertical,111,112,vertical,0.0,51072.0,55328.0,needs_review,-47.132899,-8.976988,3,2,4.695320,5.595164,0.888349,strip shifts disagree
20,123__111__horizontal,123,111,horizontal,0.0,68096.0,72352.0,needs_review,8.795972,-48.697090,3,2,4.623771,4.149305,0.883860,strip shifts disagree
21,112__113__vertical,112,113,vertical,0.0,51072.0,55328.0,needs_review,-50.725665,-9.002546,3,2,3.418103,3.415213,0.858159,strip shifts disagree
22,122__123__vertical,122,123,vertical,0.0,46816.0,51072.0,needs_review,-49.882699,-9.692044,3,2,3.879031,3.854338,0.898750,strip shifts disagree

[registration 1/30] B20971880114_colon 7__8__vertical

/home/domino/reny28/Projects/CosMX_projects/P06364_CRC_DS20250227_48371/code/Python/cosmx_cpsamv2_softstitch_pilot/cosmx_rgb_pilot.py:88: UserWarning: SpatialData is not stored in the most current format. If you want to use Zarr v3, please write the store to a new location using `sdata.write()`.
  return sd.read_zarr(str(path))
no parent found for <ome_zarr.reader.Label object at 0x7f41fc392bd0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7f9de50>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7f7e570>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7f055b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7f062d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7f07230>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7f07ef0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7f07950>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7f05d30>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7f046b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7f7e570>: None
no parent found for <ome_zarr.reader.Label object at 0x7f42b37f9790>: None
no parent found for <ome_zarr.reader.Label object at 0x7f42b37fa570>: None
no parent found for <ome_zarr.reader.Label object at 0x7f42b37fb350>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7f7d550>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7f06b70>: None
no parent found for <ome_zarr.reader.Label object at 0x7f42b37f83b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f42b37f9310>: None
no parent found for <ome_zarr.reader.Label object at 0x7f42b37f1130>: None
no parent found for <ome_zarr.reader.Label object at 0x7f42b37f1f10>: None
no parent found for <ome_zarr.reader.Label object at 0x7f42b37f2cf0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f42b37f8290>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7f04fb0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f42b37f0cb0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f42b37f3b90>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7f70ad0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7f718b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7f72690>: None
no parent found for <ome_zarr.reader.Label object at 0x7f42b37f0a10>: None
no parent found for <ome_zarr.reader.Label object at 0x7f42b37f3530>: None
no parent found for <ome_zarr.reader.Label object at 0x7f42b37f92b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f42b37fb3b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7f713d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7f739b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7f73410>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7f73050>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7f700b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f42b37fa450>: None
no parent found for <ome_zarr.reader.Label object at 0x7f42b37e5130>: None
no parent found for <ome_zarr.reader.Label object at 0x7f42b37e6570>: None
no parent found for <ome_zarr.reader.Label object at 0x7f42b37e7350>: None
no parent found for <ome_zarr.reader.Label object at 0x7f42b37e7230>: None
no parent found for <ome_zarr.reader.Label object at 0x7f42b37e7350>: None
no parent found for <ome_zarr.reader.Label object at 0x7f42b37e5df0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f42b37e5e50>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7f70470>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d15f10>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d16cf0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d17b30>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d17590>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d157f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d151f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f42b37e5e50>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d0d8b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d0e690>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d0f470>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d0e6f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d0c710>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d0d610>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d151f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d4d250>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d4e030>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d4ee10>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d15a90>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d0ff50>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d4d2b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d4cdd0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d10bf0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d11910>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d12870>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d4c470>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d4c4d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d10ad0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d13050>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d13290>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d19370>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d1a150>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d10530>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d11490>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d4c4d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d1aab0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d1abd0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d34d10>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d35af0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d1b710>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d4c470>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d11490>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d36450>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d37890>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d37770>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7e5d490>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d372f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d37170>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d10530>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7e5ddf0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7e5f230>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7e5f110>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7ea0e30>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7e5f830>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7e5df70>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d1b050>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7ea1790>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7ea2bd0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7ea39b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7ea3890>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7ea3470>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7ea2150>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7e5ec30>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7e09130>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7e0a570>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7e0b350>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7e0b230>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7e0b350>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7e09d90>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7e09e50>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7e5dc70>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7e5d490>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d11430>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d14950>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d0e570>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d36330>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7ea2450>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7e08e30>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e79fe2d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e79ff0b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e79ff050>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e79ff7d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e79fde50>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d360f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d0e570>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e79e1c70>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e79e2a50>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e79e3830>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e79e32f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e79e22d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e79e1790>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e79fd8b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e798d610>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e798e3f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e798f1d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7e09610>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d360f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e798c2f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e798d6d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e79a8fb0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e79a9d90>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e79aab70>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e798d0d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e79e22d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e79aaa50>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e79a8950>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e79884d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7989730>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e798a510>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e79a89b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e79a8a70>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7989d90>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e798ae70>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e798aff0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e79850d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7985eb0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e798bc50>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e798ae70>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e79a8230>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7986810>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7987bf0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fc1b4a70>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fc1b5850>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e79868d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e79a82f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e798ae10>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fc1b61b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fc1b75f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fc1b74d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fc0f11f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fc1b7c50>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fc1b7350>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7989d30>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fc0f1b50>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fc0f2f90>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fc0f2f30>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fc1c4b90>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fc0f32f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fc0f2810>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fc1b6f90>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fc1c54f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fc1c6930>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fc1c7710>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fc1c75f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fc1c64b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fc1c61b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fc0f28d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fc0f0cb0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fc19a2d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fc19b0b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fc19b050>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fc19a1b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fc199af0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fc199bb0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fc0f19d0>: None

[registration 2/30] B20971880114_colon 18__7__horizontal
[registration 3/30] B20971880114_colon 8__9__vertical
[registration 4/30] B20971880114_colon 19__8__horizontal
[registration 5/30] B20971880114_colon 20__9__horizontal
[registration 6/30] B20971880114_colon 18__19__vertical
[registration 7/30] B20971880114_colon 29__18__horizontal
[registration 8/30] B20971880114_colon 19__20__vertical
[registration 9/30] B20971880114_colon 30__19__horizontal
[registration 10/30] B20971880114_colon 31__20__horizontal
[registration 11/30] B20971880114_colon 29__30__vertical
[registration 12/30] B20971880114_colon 30__31__vertical
[registration 13/30] B20971880114_colon 60__61__vertical
[registration 14/30] B20971880114_colon 71__60__horizontal
[registration 15/30] B20971880114_colon 72__61__horizontal
[registration 16/30] B20971880114_colon 71__72__vertical
[registration 17/30] B20971880114_colon 91__92__vertical
[registration 18/30] B20971880114_colon 101__91__horizontal
[registration 19/30] B20971880114_colon 102__92__horizontal
[registration 20/30] B20971880114_colon 95__96__vertical
[registration 21/30] B20971880114_colon 105__95__horizontal
[registration 22/30] B20971880114_colon 96__97__vertical
[registration 23/30] B20971880114_colon 106__96__horizontal
[registration 24/30] B20971880114_colon 107__97__horizontal
[registration 25/30] B20971880114_colon 101__102__vertical
[registration 26/30] B20971880114_colon 111__101__horizontal
[registration 27/30] B20971880114_colon 112__102__horizontal
[registration 28/30] B20971880114_colon 105__106__vertical
[registration 29/30] B20971880114_colon 106__107__vertical
[registration 30/30] B20971880114_colon 111__112__vertical
[review required] Unresolved pair(s) disconnect the registration context. Review diagnostics, channel or manual corrections: ['7__8__vertical', '18__7__horizontal', '8__9__vertical', '19__8__horizontal', '18__19__vertical', '29__18__horizontal', '19__20__vertical', '30__19__horizontal', '31__20__horizontal', '29__30__vertical', '30__31__vertical', '60__61__vertical', '71__60__horizontal', '72__61__horizontal', '71__72__vertical', '91__92__vertical', '101__91__horizontal', '102__92__horizontal', '95__96__vertical', '105__95__horizontal', '96__97__vertical', '106__96__horizontal', '107__97__horizontal', '101__102__vertical', '111__101__horizontal', '105__106__vertical', '106__107__vertical', '111__112__vertical']
B20971880114_colon needs_review
Unresolved pair(s) disconnect the registration context. Review diagnostics, channel or manual corrections: ['7__8__vertical', '18__7__horizontal', '8__9__vertical', '19__8__horizontal', '18__19__vertical', '29__18__horizontal', '19__20__vertical', '30__19__horizontal', '31__20__horizontal', '29__30__vertical', '30__31__vertical', '60__61__vertical', '71__60__horizontal', '72__61__horizontal', '71__72__vertical', '91__92__vertical', '101__91__horizontal', '102__92__horizontal', '95__96__vertical', '105__95__horizontal', '96__97__vertical', '106__96__horizontal', '107__97__horizontal', '101__102__vertical', '111__101__horizontal', '105__106__vertical', '106__107__vertical', '111__112__vertical']

,pair_id,a,b,axis,nominal_gap_px,tangent0,tangent1,status,dx_px,dy_px,n_fit_good,n_holdout_good,fit_max_deviation_px,holdout_max_error_px,median_ncc,reason
0,7__8__vertical,7,8,vertical,0.0,63840.0,68096.0,needs_review,-49.331744,-9.125148,3,2,4.627823,4.653650,0.749117,strip shifts disagree
1,18__7__horizontal,18,7,horizontal,0.0,42560.0,46816.0,needs_review,9.128736,-48.632704,3,2,4.548105,4.087785,0.835516,strip shifts disagree
2,8__9__vertical,8,9,vertical,0.0,63840.0,68096.0,needs_review,-48.836468,-9.403120,3,2,3.592992,3.510895,0.768509,strip shifts disagree
3,19__8__horizontal,19,8,horizontal,0.0,46816.0,51072.0,needs_review,9.298668,-48.660307,3,1,5.067438,3.849672,0.794279,strip shifts disagree
4,20__9__horizontal,20,9,horizontal,0.0,51072.0,55328.0,candidate_pass,8.250033,-51.060083,2,2,2.430227,2.562450,0.724481,fit and held-out strips agree
5,18__19__vertical,18,19,vertical,0.0,59584.0,63840.0,needs_review,-48.680459,-9.317891,3,2,3.890922,4.094318,0.737049,strip shifts disagree
6,29__18__horizontal,29,18,horizontal,0.0,42560.0,46816.0,needs_review,8.313905,-49.121142,3,2,5.070157,4.795007,0.822662,strip shifts disagree
7,19__20__vertical,19,20,vertical,0.0,59584.0,63840.0,needs_review,-48.967374,-9.546770,3,2,3.321358,3.717658,0.808230,strip shifts disagree
8,30__19__horizontal,30,19,horizontal,0.0,46816.0,51072.0,needs_review,8.594737,-49.896012,3,2,4.292907,3.698911,0.830562,strip shifts disagree
9,31__20__horizontal,31,20,horizontal,0.0,51072.0,55328.0,needs_review,8.514259,-49.302330,3,2,4.889459,4.235089,0.825503,strip shifts disagree
10,29__30__vertical,29,30,vertical,0.0,55328.0,59584.0,needs_review,-48.769056,-9.064512,3,2,4.053702,3.954798,0.788760,strip shifts disagree
11,30__31__vertical,30,31,vertical,0.0,55328.0,59584.0,needs_review,-48.660031,-9.624602,3,2,3.584010,3.732931,0.878582,strip shifts disagree
12,60__61__vertical,60,61,vertical,0.0,42560.0,46816.0,needs_review,NaN,NaN,1,2,NaN,NaN,0.745463,insufficient reliable strips
13,71__60__horizontal,71,60,horizontal,0.0,34048.0,38304.0,needs_review,8.474918,-49.008258,2,2,1.577796,4.166290,0.779374,strip shifts disagree
14,72__61__horizontal,72,61,horizontal,0.0,38304.0,42560.0,needs_review,8.917865,-48.833372,3,2,5.318958,4.388313,0.794110,strip shifts disagree
15,71__72__vertical,71,72,vertical,0.0,38304.0,42560.0,needs_review,-48.634044,-9.903765,3,2,3.735472,3.695173,0.830099,strip shifts disagree
16,91__92__vertical,91,92,vertical,0.0,29792.0,34048.0,needs_review,-47.637587,-5.471071,3,2,3.368595,3.256313,0.756408,strip shifts disagree
17,101__91__horizontal,101,91,horizontal,0.0,29792.0,34048.0,needs_review,10.350805,-48.586166,3,2,4.661875,4.426742,0.906560,strip shifts disagree
18,102__92__horizontal,102,92,horizontal,0.0,34048.0,38304.0,needs_review,10.240465,-48.364043,3,2,4.482781,3.876189,0.858564,strip shifts disagree
19,95__96__vertical,95,96,vertical,0.0,29792.0,34048.0,needs_review,-52.113671,-7.871895,3,2,4.205556,3.809025,0.860680,strip shifts disagree
20,105__95__horizontal,105,95,horizontal,0.0,46816.0,51072.0,needs_review,10.464993,-48.883486,3,2,4.001663,3.759192,0.819992,strip shifts disagree
21,96__97__vertical,96,97,vertical,0.0,29792.0,34048.0,needs_review,-47.828056,-9.574008,3,2,3.500200,3.155122,0.835090,strip shifts disagree
22,106__96__horizontal,106,96,horizontal,0.0,51072.0,55328.0,needs_review,9.443128,-48.768223,3,2,4.359059,3.769177,0.800551,strip shifts disagree
23,107__97__horizontal,107,97,horizontal,0.0,55328.0,59584.0,needs_review,9.194971,-49.399681,3,2,4.899176,3.646321,0.811760,strip shifts disagree
24,101__102__vertical,101,102,vertical,0.0,25536.0,29792.0,needs_review,-46.528894,-5.592678,3,2,4.153666,4.239286,0.734865,strip shifts disagree
25,111__101__horizontal,111,101,horizontal,0.0,29792.0,34048.0,needs_review,9.346816,-49.315452,3,2,4.534577,3.686955,0.855478,strip shifts disagree
26,112__102__horizontal,112,102,horizontal,0.0,34048.0,38304.0,candidate_pass,10.429083,-50.867218,2,2,2.351588,2.110999,0.793756,fit and held-out strips agree
27,105__106__vertical,105,106,vertical,0.0,25536.0,29792.0,needs_review,-51.828274,-7.852857,3,2,3.355346,3.028790,0.827324,strip shifts disagree
28,106__107__vertical,106,107,vertical,0.0,25536.0,29792.0,needs_review,-47.222827,-9.057495,3,2,3.499769,3.339445,0.789907,strip shifts disagree
29,111__112__vertical,111,112,vertical,0.0,21280.0,25536.0,needs_review,-48.401361,-5.410526,3,2,4.186679,3.764098,0.881061,strip shifts disagree

## 3. Export registration QC images (300 dpi)

This is a separate image-registration gallery, not a segmentation gallery. It shows the original
pair composite, registered candidate composite, and each contributing FOV separately on the
registered axes. The mean blend here is deliberately diagnostic: persistent doubled structures
indicate a bad fit. The later default image policy uses one source per pixel.

Compare specific nuclei/crypt landmarks throughout the border. A smooth seam alone is not enough.
Files are under `<workspace>/<sample>/registration/visual_qc/index.html`.

In [4]:
EXPORT_REGISTRATION_QC = True
if EXPORT_REGISTRATION_QC:
    for sample in SAMPLE_KEYS:
        figures = stitch.export_registration_qc(config, sample, WORKSPACE, dpi=300, zoom_px=512)
        print('Gallery:', WORKSPACE / sample / 'registration' / 'visual_qc' / 'index.html')
        display(figures[['group', 'description', 'path']].head())

/home/domino/reny28/Projects/CosMX_projects/P06364_CRC_DS20250227_48371/code/Python/cosmx_cpsamv2_softstitch_pilot/cosmx_rgb_pilot.py:88: UserWarning: SpatialData is not stored in the most current format. If you want to use Zarr v3, please write the store to a new location using `sdata.write()`.
  return sd.read_zarr(str(path))
no parent found for <ome_zarr.reader.Label object at 0x7f41e7dd96d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7dda210>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7dd9010>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7dda6f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7dd8d70>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7dd9310>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7dda0f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7dbbe90>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7df8950>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7df91f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7df8cb0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7df8a10>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7db9910>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7dda390>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7c10e30>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7c11010>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7945a30>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417d4c99d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e79470b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7c10e90>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7dfb590>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7ddaed0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7935f10>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7ef2bd0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7fd00b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7ef2bd0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7dbbb90>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7c11010>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417d4cbd10>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e4604b30>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e4604dd0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e4605bb0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417d4cbd10>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7dda390>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e46043b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e4604410>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e4607d70>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e461c770>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e461d550>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e4604410>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e4606ab0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e461c4d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e461c410>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e461f2f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e4610470>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e4610ef0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e461cad0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417d4caf90>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e4611430>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e4610bf0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e4612c90>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e4613e30>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e4644890>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e4612c90>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e4607710>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e461f290>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e4644590>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e4646630>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e4647410>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e465cd70>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e4647350>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e4645670>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e46130b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e465d190>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e465dfd0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e465edb0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e467c050>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e465eb10>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e465d730>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e46469f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e467d6d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e467d970>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e467e750>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e467f530>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e467f230>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e467cf50>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e465e510>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e469d070>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e469d310>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e469e0f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e469eed0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e4647350>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e467f2f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e469e8d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e46a8470>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e46a8d10>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e46a9af0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e46aa8d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e469d850>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e467ebd0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e46aa810>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e46a9a90>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e46bc6b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e46bd490>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e46be270>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e46a8b90>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e469edb0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e46bdf70>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e46bc350>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e46d0b90>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e46d0e30>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e46d1c10>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e46bc890>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e46bfdd0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e46aacf0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e467f530>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e4611b50>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417d4ca510>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e46d04d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e4645370>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e469fa10>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e46bdfd0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e46d2b70>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e46f0110>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e46f0b90>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e46f1970>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e46d3410>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e46a8a70>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e46f0170>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e46f01d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e46f29f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e46e8890>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e46e9310>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e46f34d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e46f36b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e46e89b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e46e8470>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e46eb0b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e46f4a10>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e46f4cb0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e46ea2d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e46eb710>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e46f3110>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e46f42f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e46f6a50>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e46f6f90>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417eae5190>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e46f6ed0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e46f6750>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e46eae70>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417eae4410>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417eae63f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417eae71d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417eac4350>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417eae6f30>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417eae63f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e46f4a70>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417eac4f50>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417eac5d90>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417eac6b70>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417eac7d70>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417eac6150>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417eac7350>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417eae4470>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417eab48f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417eab5730>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417eab6510>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417eab72f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417eab6f90>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417eab55b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417eac7770>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417ea94e30>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417ea950d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417ea95eb0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417ea96c90>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417eae5550>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417eab66f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417ea969f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417ea787d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417ea78a70>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417ea79850>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417ea7a630>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417ea969f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417eab55b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417ea7a4b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417ea7bef0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417ea70770>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417ea711f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417ea71fd0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417ea78dd0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417ea97170>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417ea71610>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417ea70290>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417ea588f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417ea58b90>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417ea59970>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417ea721b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417ea73770>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417ea7a990>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417eab72f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e46f5070>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e46f5130>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417ea597f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e46f5070>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417ea96ff0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417ea734d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417ea5b830>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417ea38650>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417ea388f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417ea396d0>: None

Gallery: /host_root/nethome/reny28/Projects/CosMX_projects/P06364_CRC_DS20250227_48371/tmp/DS-20250227-48371/cpsam_v2_rgb_softstitch_pilot_v1_registered_owner_v1/B20317610105_colon/registration/visual_qc/index.html

,group,description,path
0,87__88__vertical,before | candidate_pass,/host_root/nethome/reny28/Projects/CosMX_proje...
1,99__87__horizontal,before | needs_review,/host_root/nethome/reny28/Projects/CosMX_proje...
2,88__89__vertical,before | candidate_pass,/host_root/nethome/reny28/Projects/CosMX_proje...
3,100__88__horizontal,before | needs_review,/host_root/nethome/reny28/Projects/CosMX_proje...
4,101__89__horizontal,before | needs_review,/host_root/nethome/reny28/Projects/CosMX_proje...

/home/domino/reny28/Projects/CosMX_projects/P06364_CRC_DS20250227_48371/code/Python/cosmx_cpsamv2_softstitch_pilot/cosmx_rgb_pilot.py:88: UserWarning: SpatialData is not stored in the most current format. If you want to use Zarr v3, please write the store to a new location using `sdata.write()`.
  return sd.read_zarr(str(path))
no parent found for <ome_zarr.reader.Label object at 0x7f4169b44ad0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fc3f6e10>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fc34c890>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fc34fad0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fc34c1d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fc34cdd0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7fbe330>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7f36b10>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fc37a750>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fc34dc70>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7f0ca70>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fc39f7d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fc39e930>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fc39cbf0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fc39f290>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fc39f230>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fc34cb30>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fc34d790>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e41e1fd0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e41e36b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f42b366a6f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e41e2f30>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e41e2030>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fc39c830>: None
no parent found for <ome_zarr.reader.Label object at 0x7f42b36687d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f42b366a030>: None
no parent found for <ome_zarr.reader.Label object at 0x7f42b366a9f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f42b366b9b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f42b366a9f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f42b3668590>: None
no parent found for <ome_zarr.reader.Label object at 0x7f42b3669eb0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e41e25d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fc390c50>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fc3902f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fc3901d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fc392c90>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fc390770>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fc391eb0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f42b3668bf0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e41a47d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e41a5bb0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e41a4170>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e41a6570>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e41a5df0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e41a4230>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fc3913d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e41f40b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e41f6c30>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e41f7cb0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e41f7c50>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e41f49b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e41f60f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e41a4230>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7f9c050>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7f9d7f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7f9c530>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7f9f710>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7f9ee70>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7f9edb0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e41f4e90>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7f7c770>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7f7cef0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7f7f470>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e41a44d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e41a7a10>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7f7f830>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7f7f770>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7f71130>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7f70890>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7f71310>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7f7c710>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7f7f350>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e41f66f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fc392510>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fc39dbb0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7f718b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7f72390>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7f72c90>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e41a60f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e41a4050>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7f7f110>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d14530>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d14bf0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d167b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d17410>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d16b70>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e41f66f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e41f5850>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d0dc70>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d0fb30>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d0e5d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7f7e810>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7f7c710>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d0e630>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d0c7d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7e095b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7e0ad50>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7e0a870>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d0d070>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d14e30>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7e08b90>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7e08530>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e79fdc10>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e79fe2d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e79ff3b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7e08650>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d0f9b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e79fd250>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e79ffa70>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e79e3110>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e79e34d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e79e26f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e79e1970>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e79e34d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e79fdaf0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7e08170>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fca742f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fcb7fbf0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fcb7cd10>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fcb7eed0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fcb7c590>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7e08170>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e79e2db0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f416aa576b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e45fcfb0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e45fdd90>: None
no parent found for <ome_zarr.reader.Label object at 0x7f416aa55490>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7e0b3b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7e0aa50>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e45fe6f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e45ff770>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e46bc9b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e46bd730>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e45ff5f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fcb7eed0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41fcb7f8f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e46be090>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e46bf4d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e46bf3b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e469d0d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e46bfb30>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e46be6f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e79e3950>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e469da30>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e469ee70>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e469fa70>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417c940a70>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e469ef30>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e469dfd0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e46bee10>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417c9413d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417c942810>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417c9435f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417c9434d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417c9435f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417c942150>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417c941490>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e46bd2b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f416aa57410>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e79fccb0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7d147d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e79fccb0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e79ff7d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e469d970>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7fbca10>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7fbe930>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e7df83b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417c941d90>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417c940230>: None
no parent found for <ome_zarr.reader.Label object at 0x7f4169a833b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f4169a81cd0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f4169a80650>: None
no parent found for <ome_zarr.reader.Label object at 0x7f41e790be30>: None
no parent found for <ome_zarr.reader.Label object at 0x7f4169a825d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f416aa572f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417ea7b1d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417ea788f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417c92ae10>: None
no parent found for <ome_zarr.reader.Label object at 0x7f4169b44290>: None
no parent found for <ome_zarr.reader.Label object at 0x7f4169b44410>: None
no parent found for <ome_zarr.reader.Label object at 0x7f4169a832f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417c929d30>: None
no parent found for <ome_zarr.reader.Label object at 0x7f4169b3e930>: None
no parent found for <ome_zarr.reader.Label object at 0x7f4169b3d250>: None
no parent found for <ome_zarr.reader.Label object at 0x7f4169b3e990>: None
no parent found for <ome_zarr.reader.Label object at 0x7f4169b3e810>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417ea788f0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f417ea7b1d0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f4169af2d50>: None
no parent found for <ome_zarr.reader.Label object at 0x7f4169af1670>: None
no parent found for <ome_zarr.reader.Label object at 0x7f4169b44350>: None
no parent found for <ome_zarr.reader.Label object at 0x7f4169b446b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f4169b3f0b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f4169af1e50>: None
no parent found for <ome_zarr.reader.Label object at 0x7f4169ae3e30>: None
no parent found for <ome_zarr.reader.Label object at 0x7f4169ae2930>: None
no parent found for <ome_zarr.reader.Label object at 0x7f4169af0590>: None
no parent found for <ome_zarr.reader.Label object at 0x7f4169b3f0b0>: None
no parent found for <ome_zarr.reader.Label object at 0x7f4169b3f770>: None
no parent found for <ome_zarr.reader.Label object at 0x7f4169ae0410>: None

Gallery: /host_root/nethome/reny28/Projects/CosMX_projects/P06364_CRC_DS20250227_48371/tmp/DS-20250227-48371/cpsam_v2_rgb_softstitch_pilot_v1_registered_owner_v1/B20971880114_colon/registration/visual_qc/index.html

,group,description,path
0,7__8__vertical,before | needs_review,/host_root/nethome/reny28/Projects/CosMX_proje...
1,18__7__horizontal,before | needs_review,/host_root/nethome/reny28/Projects/CosMX_proje...
2,8__9__vertical,before | needs_review,/host_root/nethome/reny28/Projects/CosMX_proje...
3,19__8__horizontal,before | needs_review,/host_root/nethome/reny28/Projects/CosMX_proje...
4,20__9__horizontal,before | candidate_pass,/host_root/nethome/reny28/Projects/CosMX_proje...

## 4. Audit transcript observations in the registered overlap

This does **not delete anything**. It moves each source observation using the image-derived FOV
translation, preserves its frozen observation ID, and inspects mutual-nearest same-feature pairs
across different FOVs at several radii. These are **candidate correspondences**, not proven
molecule identities. The shuffled-feature comparison is descriptive, not an FDR estimate.

No same-FOV molecules are paired or collapsed. Z is not assumed co-registered across acquisitions;
its difference is recorded in the detailed candidate table. The radii are diagnostics, not deletion
thresholds.

The tables report whether a prospective spatial-ownership rule would retain exactly one, both,
or neither observation in a candidate pair. Both-kept/neither-kept cases near the ownership seam
need inspection: localization error and incomplete redetection mean spatial ownership is not
perfect molecular de-duplication.

Read `transcript_overlap_summary.csv` and `transcript_candidate_pairs.parquet`. Do not infer that
all observations excluded by ownership are duplicate molecules. Confirm that both overlapping
acquisitions actually contain transcript observations; otherwise leave ownership disabled.

In [5]:
RUN_TRANSCRIPT_AUDIT = True
if RUN_TRANSCRIPT_AUDIT:
    for sample in SAMPLE_KEYS:
        if candidates[sample]['registration_status'] != 'candidate_ready':
            print('Skipped transcript audit until registration is resolved:', sample)
            continue
        transcript_qc = stitch.audit_transcript_overlaps(
            config, sample, WORKSPACE, radii_um=(0.12, 0.25, 0.50))
        display(transcript_qc)

Skipped transcript audit until registration is resolved: B20317610105_colon
Skipped transcript audit until registration is resolved: B20971880114_colon

## Next checkpoint

Proceed to notebook 07 only after (1) the source structures align, (2) the translation diagnostics
are acceptable, and (3) duplicated acquisition observations are supported. Keep the original
pilot caches unchanged. This notebook has not edited images, labels, points, tables, or source
transformation metadata. Only the separate workspace has been written.